import { Geist, Geist_Mono, Piedra } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import ContactOrder from "@/components/ContactOrder/ContactOrder";
import WhatsAppButton from "@/components/WhatsAppButton/WhatsAppButton";
import Footer from "@/sections/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const piedra = Piedra({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-piedra",
});

export const metadata = {
  title: "Resturant landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${piedra.variable}`}>
      <body className="antialiased font-piedra">
        <Header />
        {children}
        <WhatsAppButton />
    <ContactOrder />
     <Footer />
      </body>
    </html>
  );
}
