import { Geist, Geist_Mono, Piedra } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const piedra = Piedra({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-piedra",
});

export const metadata = {
  title: "Resturant landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${piedra.variable}`}>
      <body className="antialiased font-piedra">
        {children}
      </body>
    </html>
  );
}
